#!/usr/bin/php
<?php

/*
Usage:
  ./functions_help.php                 list all functions with their docs
  ./functions_help.php --name=<fn>     show a single function
  ./functions_help.php --file=<path>   document another PHP file (default: soap_functions.php)
  ./functions_help.php --json          machine-readable output

Auto-generated reference for the library functions, built from their PHPDoc
blocks (name, summary, @param, @return). Pure static analysis - it does not run
the code, so no ISPConfig connection is needed.
*/

$arrArg = array();
foreach ($argv as $arg) {
	if (preg_match('/^--([^=]+)(?:=(.*))?$/', $arg, $m)) {
		$arrArg[$m[1]] = isset($m[2]) ? $m[2] : true;
	}
}

$file = isset($arrArg['file']) ? $arrArg['file'] : __DIR__ . '/soap_functions.php';
if (!is_file($file)) {
	die('File not found: ' . $file . "\n");
}

// Parse a PHPDoc block into summary / @param / @return
function parseDocComment($doc) {
	$result = array('summary' => '', 'params' => array(), 'return' => null);
	if ($doc === null) {
		return $result;
	}

	$summaryLines = array();
	$inSummary = true;

	foreach (preg_split('/\r?\n/', $doc) as $line) {
		// Strip the /** ... */ decoration and leading "* "
		$line = preg_replace('#^\s*/\*\*+#', '', $line);
		$line = preg_replace('#\*+/\s*$#', '', $line);
		$line = preg_replace('#^\s*\*\s?#', '', $line);
		$line = rtrim($line);

		if (preg_match('/^@param\s+(\S+)\s+(\$\S+)\s*(.*)$/', $line, $m)) {
			$inSummary = false;
			$result['params'][] = array('type' => $m[1], 'name' => $m[2], 'desc' => trim($m[3]));
		} elseif (preg_match('/^@return\s+(\S+)\s*(.*)$/', $line, $m)) {
			$inSummary = false;
			$result['return'] = array('type' => $m[1], 'desc' => trim($m[2]));
		} elseif (preg_match('/^@/', $line)) {
			$inSummary = false;
		} elseif ($inSummary) {
			$summaryLines[] = $line;
		}
	}

	// Collapse the summary into trimmed, non-empty lines
	$summaryLines = array_values(array_filter(array_map('trim', $summaryLines), 'strlen'));
	$result['summary'] = implode(' ', $summaryLines);

	return $result;
}

// Walk the tokens, pairing each top-level function with the doc block right before it
$tokens = token_get_all(file_get_contents($file));
$count = count($tokens);
$functions = array();
$lastDoc = null;

for ($i = 0; $i < $count; $i++) {
	$tok = $tokens[$i];

	if (is_array($tok)) {
		if ($tok[0] === T_DOC_COMMENT) {
			$lastDoc = $tok[1];
			continue;
		}
		if ($tok[0] === T_WHITESPACE) {
			continue; // keep the pending doc block across blank lines
		}
		if ($tok[0] === T_FUNCTION) {
			// The next string token is the function name (closures have none)
			$j = $i + 1;
			while ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) {
				$j++;
			}
			$name = ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_STRING) ? $tokens[$j][1] : null;

			if ($name !== null) {
				// Collect the raw parameter list between the matching parentheses
				while ($j < $count && $tokens[$j] !== '(') {
					$j++;
				}
				$depth = 0;
				$paramStr = '';
				for (; $j < $count; $j++) {
					$txt = is_array($tokens[$j]) ? $tokens[$j][1] : $tokens[$j];
					if ($txt === '(') {
						$depth++;
						if ($depth === 1) {
							continue;
						}
					}
					if ($txt === ')') {
						$depth--;
						if ($depth === 0) {
							break;
						}
					}
					$paramStr .= $txt;
				}

				$doc = parseDocComment($lastDoc);
				$doc['name'] = $name;
				$doc['signature'] = $name . '(' . trim(preg_replace('/\s+/', ' ', $paramStr)) . ')';
				$functions[] = $doc;
				$i = $j;
			}
		}
		$lastDoc = null;
	} else {
		$lastDoc = null;
	}
}

// Optional single-function filter
if (isset($arrArg['name'])) {
	$functions = array_values(array_filter($functions, function ($f) use ($arrArg) {
		return $f['name'] === $arrArg['name'];
	}));
	if (!$functions) {
		die('Function not found: ' . $arrArg['name'] . "\n");
	}
}

if (isset($arrArg['json'])) {
	echo json_encode(array(
		'file'  => $file,
		'count' => count($functions),
		'functions' => $functions,
	), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
	exit(0);
}

if (isset($arrArg['markdown'])) {
	echo '# Functions — `' . basename($file) . "`\n\n";
	echo "Auto-generated by `functions_help.php` from PHPDoc blocks. Do not edit by hand;\n";
	echo "regenerate with `./functions_help.php --markdown > README-FUNCTIONS.md`.\n\n";
	echo count($functions) . " functions.\n\n";

	foreach ($functions as $f) {
		echo '- [' . $f['name'] . '](#' . strtolower($f['name']) . ")\n";
	}
	echo "\n---\n\n";

	foreach ($functions as $f) {
		echo '## ' . $f['name'] . "\n\n";
		echo "```php\n" . $f['signature'] . "\n```\n\n";
		if ($f['summary'] !== '') {
			echo $f['summary'] . "\n\n";
		}
		if ($f['params']) {
			echo "| Param | Type | Description |\n|-------|------|-------------|\n";
			foreach ($f['params'] as $p) {
				echo '| `' . $p['name'] . '` | ' . str_replace('|', '\\|', $p['type']) . ' | ' . str_replace('|', '\\|', $p['desc']) . " |\n";
			}
			echo "\n";
		}
		if ($f['return'] !== null) {
			echo '**Returns:** `' . $f['return']['type'] . '`' . ($f['return']['desc'] !== '' ? ' — ' . $f['return']['desc'] : '') . "\n\n";
		}
	}
	exit(0);
}

// Human-readable output
echo basename($file) . ' - ' . count($functions) . " function(s)\n\n";

foreach ($functions as $f) {
	echo $f['signature'] . "\n";
	if ($f['summary'] !== '') {
		echo '  ' . $f['summary'] . "\n";
	}
	foreach ($f['params'] as $p) {
		echo '    @param  ' . $p['name'] . '  (' . $p['type'] . ')' . ($p['desc'] !== '' ? '  ' . $p['desc'] : '') . "\n";
	}
	if ($f['return'] !== null) {
		echo '    @return (' . $f['return']['type'] . ')' . ($f['return']['desc'] !== '' ? '  ' . $f['return']['desc'] : '') . "\n";
	}
	echo "\n";
}
